### ISSUE TITLE
Data collection: sentences and geographic origin

### ISSUE THREAD

**Issue by dabao12321** [dabao12321/geolang#1]
Currently, I have a large corpus of words unique to geographical regions of the U.S. While this data is useful, it has its limitations (ex. some words seem too rare/specific to be informative, or lack context). 

To build a network to guess where a speaker/writer is from, we would like more robust training data. Specifically, we need authentic sentences labeled with the author's geographical origin (within the U.S.). 

Places to start looking may include:
- blog posts
- transcribed telephone calls 
- closed captions from local news sources
- local advertisements
- twitter

Could anyone find/create this dataset?

**Comment by kabirnagral** [comment]
[This](http://www4.uwm.edu/FLL/linguistics/dialect/maps.html) might be useful to you, although I'm not sure if it addresses your issue.

**Comment by dabao12321** [comment]
@kabirnagral Thanks, I've taken a look through there as well!

I think that, between my current data and Gerardo's transcriptions, I have enough to work with. Closing issue for now!

**Comment by dabao12321** [comment]
Fixed by #2
