### ISSUE TITLE
Convert .trn to .txt data

### ISSUE THREAD

**Issue by dabao12321** [dabao12321/geolang#4]
Currently, the transcription data (under SBData folder) is stored in a .trn file and the corresponding metadata is stored in a .csv file. It'd be great if this data could be presented in a simpler way to make text processing easier.

#### To Do:
- [x] Convert .trn to .txt data
- [x] Link .txt datafiles to metadata labels (adding text link to .csv file or adding label to .txt file)

**Comment by sarmxzh** [comment]
@dabao12321 I'll work on this. I've converted all but two (SBC037 and SBC060) .trn files into .txt files, and for the remaining two, there is an error regarding the encoding of the files. Do you happen to know what type of encoding these files use?

**Comment by dabao12321** [comment]
refer to pull #9
