### ISSUE TITLE
Organize transcription data

### ISSUE THREAD

**Issue by dabao12321** [dabao12321/geolang#7]
The .txt transcriptions and corresponding metadata is quite disorganized right now, with a lot of clutter in the .txt files and unstructured labeling in the .csv metadata. Specifically, the label indexes do not correspond with the file numbers, since there are sometimes multiple speakers in one file.

Can someone clearly correlate the geographic origin of the speaker (don't need name) with their speech in a CSV format? It should be organized in a similar format as the cleaned_dare_corpus.csv file:

ex. index, dialect (location by state), word/speech (**one full sentence**).

**Comment by ghost** [comment]
See pull request

**Comment by dabao12321** [comment]
*see pull #9
